FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# foodfinder

Backend API for FoodFinder.

## Distributors Collection [/distributors]

### List All Distributors [GET]

+ Response 200 (application/json)

        [
            {
                "name": "ABRAHAM HOUSE, INC",
                "phone": "7182929321",
                "street": "340 WILLIS AVENUE",
                "city": "The Bronx",
                "days": "SAT",
                "hours": "6:30-7:30AM"
            }
        ]